export const CONTRACT_ADDRESS = "CC4J3QDHYNVWSRYHEI3R6I74QJWVVYLP3HBZTRRMDX7JUV4IDLPXSEPQ";
export const FACTORY_CONTRACT_ADDRESS = "CCRDSIAHH4LJ7XUFN6AZ3WUARX24H62L4D3ADUSJHZMHHFC7LUOXEOOY";
export const Network = "https://rpc-futurenet.stellar.org";
export const SUPPORTED_NETWORK = "FUTURENET";

