//export const CONTRACT_ADDRESS = "CC4J3QDHYNVWSRYHEI3R6I74QJWVVYLP3HBZTRRMDX7JUV4IDLPXSEPQ";
// export const FACTORY_CONTRACT_ADDRESS = "CAWFTIEPHDRGJEGKK3KYCRWW53T2H7L23W3KOGNAE7ELUDB4UDUBQUCG";
//export const FACTORY_CONTRACT_ADDRESS = "CCSWCLGTOFBH32NK3RWEFY3MG2USRA6C36PM6EA7NSSGSFZSS3ZVVS7N";

// export const FACTORY_CONTRACT_ADDRESS = "CCRDSIAHH4LJ7XUFN6AZ3WUARX24H62L4D3ADUSJHZMHHFC7LUOXEOOY";

//export const Network = "https://rpc-futurenet.stellar.org";



// export const CONTRACT_ADDRESS = "CC4J3QDHYNVWSRYHEI3R6I74QJWVVYLP3HBZTRRMDX7JUV4IDLPXSEPQ";
// export const FACTORY_CONTRACT_ADDRESS = "CCRDSIAHH4LJ7XUFN6AZ3WUARX24H62L4D3ADUSJHZMHHFC7LUOXEOOY";
// export const Network = "https://rpc-futurenet.stellar.org";
// //export const SUPPORTED_NETWORK = "FUTURENET";

export const CONTRACT_ADDRESS = "CC4J3QDHYNVWSRYHEI3R6I74QJWVVYLP3HBZTRRMDX7JUV4IDLPXSEPQ";
export const FACTORY_CONTRACT_ADDRESS = "CCGVCTV6US4JYE443Y66RPBKLUPHPKC7LZ6SWBC7U7P3JSNXF4Q65YBF";

export const Network = "https://rpc-futurenet.stellar.org";
export const SUPPORTED_NETWORK = "FUTURENET";
export const SUPPORTED_NETWORK1 = "STANDALONE"
